project:
  type: book
  output-dir: docs
lang: pl

book:
  title: "Rachunek prawdopodobieństwa (AI)"
  author: "Piotr Dyszewski"
  search: true
  date: "6/8/2026"
  page-footer: "Copyright 2026, Piotr Dyszewski"
  downloads: [pdf]
  repo-url: https://github.com/pdyszewski/RPAI/
  cover-image: Cover/cover.png
  chapters:
    - index.qmd
    - sylabus.qmd
    - part: "Notatki"
      chapters:
        - intro.qmd
        - aksjomaty.qmd
        #- klasyczne.qmd
        #- summary.qmd
        - references.qmd
    - part: "Listy zadań"
      chapters:
        - lista1.qmd

bibliography: references.bib

format:
  html:
    fig-responsive: true
    code-fold: true
    code-summary: "Pokaż kod"
    code-copy: true
    code-overflow: wrap
    css: styles.css
    theme:
      - Slate
  pdf:
    documentclass: scrreprt
    include-in-header:
      text: |
        \usepackage{amsfonts}
        \DeclareMathAlphabet{\mathbb}{U}{msb}{m}{n}



